spring:
  application.name: PRODUCT-CATALOG

config:
  datasource:
    url: jdbc:mysql://localhost:3310/products_db
    username: "root"
    password: "123456"
    driverClassName: "com.mysql.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.example.product: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true